[general]
import = ["~/.config/alacritty/current_scheme.toml"]

[window]
opacity = 0.85
padding = { x = 20, y = 15 }
startup_mode = "Maximized"
decorations_theme_variant = "Dark"

[scrolling]
multiplier = 5

[font]
normal = { family = "IosevkaTerm NF", style = "SemiBold" }
italic = { style = "SemiBold Italic" }
size = 15

[cursor.style]
shape = "Beam"
blinking = "On"
