[general]
import = ["~/.config/alacritty/current_scheme.toml"]

[window]
opacity = 0.85
padding = { x = 20, y = 15 }
startup_mode = "Maximized"

[font]
normal = { family = "IosevkaTerm NF", style = "SemiBold" }
italic = { style = "SemiBold Italic" }
size = 15
# builtin_box_drawing = false
# offset = { x = 2, y = 2 }

[cursor.style]
shape = "Beam"
blinking = "On"
