[schemes.sea_shells.colors.primary]
background = "#09141B"
foreground = "#DEB88D"

[schemes.sea_shells.colors.normal]
black = "#17384C"
red = "#D15123"
green = "#027C9B"
yellow = "#FCA02F"
blue = "#1E4950"
magenta = "#68D4F1"
cyan = "#87ACB4"
white = "#DEB88D"

[schemes.sea_shells.colors.bright]
black = "#434B53"
red = "#D48678"
green = "#628D98"
yellow = "#FDD39F"
blue = "#1BBCDD"
magenta = "#BBE3EE"
cyan = "#50A3B5"
white = "#FEE4CE"

[schemes.sea_shells.colors.selection]
background = "#1E4962"
foreground = "#FEE4CE"

[schemes.sea_shells.colors.cursor]
cursor = "#FCA02F"

[schemes.rose_pine_moon.colors.primary]
foreground = "#E0DEF4"
background = "#232136"

[schemes.rose_pine_moon.colors.normal]
black = "#393552"
red = "#EB6F92"
green = "#9CCFD8"
yellow = "#F6C177"
blue = "#3E8FB0"
magenta = "#C4A7E7"
cyan = "#EA9A97"
white = "#E0DEF4"

[schemes.rose_pine_moon.colors.bright]
black = "#6E6A86"
red = "#EB6F92"
green = "#9CCFD8"
yellow = "#F6C177"
blue = "#3E8FB0"
magenta = "#C4A7E7"
cyan = "#EA9A97"
white = "#E0DEF4"

[schemes.rose_pine_moon.colors.selection]
text = "#E0DEF4"
background = "#44415A"

[schemes.rose_pine_moon.colors.cursor]
cursor = "#56526E"

[schemes.gotham.colors.primary]
background = "#0A0F14"
foreground = "#98D1CE"

[schemes.gotham.colors.normal]
black = "#0A0F14"
red = "#C33027"
green = "#26A98B"
yellow = "#EDB54B"
blue = "#195465"
magenta = "#4E5165"
cyan = "#33859D"
white = "#98D1CE"

[schemes.gotham.colors.bright]
black = "#10151B"
red = "#D26939"
green = "#081F2D"
yellow = "#245361"
blue = "#093748"
magenta = "#888BA5"
cyan = "#599CAA"
white = "#D3EBE9"

[schemes.gotham.colors.selection]
background = "#1E4962"
foreground = "#FEE4CE"

[schemes.gotham.colors.cursor]
cursor = "#FCA02F"

[schemes.kanagawa.colors.primary]
background = "#1F1F28"
foreground = "#DCD7BA"

[schemes.kanagawa.colors.normal]
black = "#090618"
red = "#C34043"
green = "#76946A"
yellow = "#C0A36E"
blue = "#7E9CD8"
magenta = "#957FB8"
cyan = "#6A9589"
white = "#DCD7BA"

[schemes.kanagawa.colors.bright]
black = "#727169"
red = "#E82424"
green = "#98BB6C"
yellow = "#E6C384"
blue = "#7FB4CA"
magenta = "#938AA9"
cyan = "#7AA89F"
white = "#C8C093"

[schemes.kanagawa.colors.selection]
background = "#2D4F67"
foreground = "#C8C093"

[schemes.kanagawa.colors.cursor]
cursor = "#969384"

[schemes.catpuccin_mocha.colors.primary]
background = "#1e1e2e"
foreground = "#cdd6f4"

[schemes.catpuccin_mocha.colors.normal]
black = "#45475a"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#bac2de"

[schemes.catpuccin_mocha.colors.bright]
black = "#585b70"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#a6adc8"

[schemes.catpuccin_mocha.colors.selection]
background = "#f5e0dc"
foreground = "#1e1e2e"

[schemes.catpuccin_mocha.colors.cursor]
cursor = "#f5e0dc"
