[colors.primary]
background = "#09141B"
foreground = "#DEB88D"

[colors.normal]
black = "#17384C"
red = "#D15123"
green = "#027C9B"
yellow = "#FCA02F"
blue = "#2E6973"
magenta = "#68D4F1"
cyan = "#87ACB4"
white = "#DEB88D"

[colors.bright]
black = "#434B53"
red = "#D48678"
green = "#628D98"
yellow = "#FDD39F"
blue = "#1BBCDD"
magenta = "#BBE3EE"
cyan = "#50A3B5"
white = "#FEE4CE"

[colors.selection]
background = "#1E4962"
foreground = "#FEE4CE"

[colors.cursor]
cursor = "#FCA02F"
