[schemes.sea_shells.colors.primary]
background = "#09141B"
foreground = "#DEB88D"

[schemes.sea_shells.colors.normal]
black = "#17384C"
red = "#D15123"
green = "#027C9B"
yellow = "#FCA02F"
blue = "#1E4950"
magenta = "#68D4F1"
cyan = "#87ACB4"
white = "#DEB88D"

[schemes.sea_shells.colors.bright]
black = "#434B53"
red = "#D48678"
green = "#628D98"
yellow = "#FDD39F"
blue = "#1BBCDD"
magenta = "#BBE3EE"
cyan = "#50A3B5"
white = "#FEE4CE"

[schemes.sea_shells.colors.selection]
background = "#1E4962"
foreground = "#FEE4CE"

[schemes.sea_shells.colors.cursor]
cursor = "#FCA02F"

[schemes.rose_pine_moon.colors.primary]
background = "#232136"
foreground = "#E0DEF4"

[schemes.rose_pine_moon.colors.normal]
black = "#393552"
red = "#EB6F92"
green = "#9CCFD8"
yellow = "#F6C177"
blue = "#3E8FB0"
magenta = "#C4A7E7"
cyan = "#EA9A97"
white = "#E0DEF4"

[schemes.rose_pine_moon.colors.bright]
black = "#6E6A86"
red = "#EB6F92"
green = "#9CCFD8"
yellow = "#F6C177"
blue = "#3E8FB0"
magenta = "#C4A7E7"
cyan = "#EA9A97"
white = "#E0DEF4"

[schemes.rose_pine_moon.colors.selection]
background = "#44415A"
foreground = "#E0DEF4"

[schemes.rose_pine_moon.colors.cursor]
cursor = "#56526E"

[schemes.gotham2.colors.primary]
background = "#0A0F14"
foreground = "#98D1CE"

[schemes.gotham2.colors.normal]
black = "#1A232C"
red = "#C33027"
green = "#26A98B"
yellow = "#E1AA46"
blue = "#1C5A6C"
magenta = "#4E5165"
cyan = "#33859D"
white = "#98D1CE"

[schemes.gotham2.colors.bright]
black = "#57606D"
red = "#D26939"
green = "#31D2AD"
yellow = "#FABE50"
blue = "#207B9C"
magenta = "#888BA5"
cyan = "#599CAA"
white = "#D3EBE9"

[schemes.gotham2.colors.selection]
background = "#4E6174"
foreground = "#D3EBE9"

[schemes.gotham2.colors.cursor]
cursor = "#98D1CE"

[schemes.kanagawa.colors.primary]
background = "#1F1F28"
foreground = "#DCD7BA"

[schemes.kanagawa.colors.normal]
black = "#090618"
red = "#C34043"
green = "#76946A"
yellow = "#C0A36E"
blue = "#7E9CD8"
magenta = "#957FB8"
cyan = "#6A9589"
white = "#DCD7BA"

[schemes.kanagawa.colors.bright]
black = "#727169"
red = "#E82424"
green = "#98BB6C"
yellow = "#E6C384"
blue = "#7FB4CA"
magenta = "#938AA9"
cyan = "#7AA89F"
white = "#C8C093"

[schemes.kanagawa.colors.selection]
background = "#2D4F67"
foreground = "#C8C093"

[schemes.kanagawa.colors.cursor]
cursor = "#969384"

[schemes.breath_silverfox.colors.primary]
background = "#1E2229"
foreground = "#BBBBBB"

[schemes.breath_silverfox.colors.normal]
black = "#1E2229"
red = "#ED1515"
green = "#44853A"
yellow = "#F67400"
blue = "#1D99F3"
magenta = "#9B59B6"
cyan = "#1ABC9C"
white = "#FCFCFC"

[schemes.breath_silverfox.colors.bright]
black = "#7F8C8D"
red = "#C0392B"
green = "#55A649"
yellow = "#FDBC4B"
blue = "#3DAEE9"
magenta = "#8E44AD"
cyan = "#16A085"
white = "#FFFFFF"

[schemes.breath_silverfox.colors.selection]
background = "#545D6D"
foreground = "#FFFFFF"

[schemes.breath_silverfox.colors.cursor]
cursor = "#BBBBBB"

[schemes.lavandula2.colors.primary]
background = "#050014"
foreground = "#817A8C"

[schemes.lavandula2.colors.normal]
black = "#140033"
red = "#7D1625"
green = "#276458"
yellow = "#B39B68"
blue = "#746CB8"
magenta = "#5A3F7F"
cyan = "#58777F"
white = "#817A8C"

[schemes.lavandula2.colors.bright]
black = "#63537C"
red = "#E05167"
green = "#52E0C4"
yellow = "#E0C386"
blue = "#8E87E0"
magenta = "#A776E0"
cyan = "#9AD4E0"
white = "#A69EB4"

[schemes.lavandula2.colors.selection]
background = "#3B2369"
foreground = "#A69EB4"

[schemes.lavandula2.colors.cursor]
cursor = "#817A8C"

[schemes.neutron.colors.primary]
background = "#1C1E22"
foreground = "#E6E8EF"

[schemes.neutron.colors.normal]
black = "#23252B"
red = "#B54036"
green = "#5AB977"
yellow = "#DEB566"
blue = "#6A7C93"
magenta = "#A4799D"
cyan = "#3F94A8"
white = "#E6E8EF"

[schemes.neutron.colors.bright]
black = "#868D9F"
red = "#B54036"
green = "#5AB977"
yellow = "#DEB566"
blue = "#6A7C93"
magenta = "#A4799D"
cyan = "#3F94A8"
white = "#EBEDF2"

[schemes.neutron.colors.selection]
background = "#636973"
foreground = "#EBEDF2"

[schemes.neutron.colors.cursor]
cursor = "#E6E8EF"
