[schemes.sea_shells.colors.primary]
background = "#09141B"
foreground = "#DEB88D"

[schemes.sea_shells.colors.normal]
black = "#17384C"
red = "#D15123"
green = "#027C9B"
yellow = "#FCA02F"
blue = "#2E6973"
magenta = "#68D4F1"
cyan = "#87ACB4"
white = "#DEB88D"

[schemes.sea_shells.colors.bright]
black = "#434B53"
red = "#D48678"
green = "#628D98"
yellow = "#FDD39F"
blue = "#1BBCDD"
magenta = "#BBE3EE"
cyan = "#50A3B5"
white = "#FEE4CE"

[schemes.sea_shells.colors.selection]
background = "#1E4962"
foreground = "#FEE4CE"

[schemes.sea_shells.colors.cursor]
cursor = "#FCA02F"

[schemes.rose_pine_moon.colors.primary]
background = "#232136"
foreground = "#E0DEF4"

[schemes.rose_pine_moon.colors.normal]
black = "#393552"
red = "#EB6F92"
green = "#9CCFD8"
yellow = "#F6C177"
blue = "#3E8FB0"
magenta = "#C4A7E7"
cyan = "#EA9A97"
white = "#E0DEF4"

[schemes.rose_pine_moon.colors.bright]
black = "#6E6A86"
red = "#EB6F92"
green = "#9CCFD8"
yellow = "#F6C177"
blue = "#3E8FB0"
magenta = "#C4A7E7"
cyan = "#EA9A97"
white = "#E0DEF4"

[schemes.rose_pine_moon.colors.selection]
background = "#44415A"
foreground = "#E0DEF4"

[schemes.rose_pine_moon.colors.cursor]
cursor = "#56526E"

[schemes.gotham2.colors.primary]
background = "#0A0F14"
foreground = "#98D1CE"

[schemes.gotham2.colors.normal]
black = "#1A232C"
red = "#C33027"
green = "#26A98B"
yellow = "#E1AA46"
blue = "#1C5A6C"
magenta = "#4E5165"
cyan = "#33859D"
white = "#98D1CE"

[schemes.gotham2.colors.bright]
black = "#57606D"
red = "#D26939"
green = "#31D2AD"
yellow = "#FABE50"
blue = "#207B9C"
magenta = "#888BA5"
cyan = "#599CAA"
white = "#D3EBE9"

[schemes.gotham2.colors.selection]
background = "#4E6174"
foreground = "#D3EBE9"

[schemes.gotham2.colors.cursor]
cursor = "#98D1CE"

[schemes.kanagawa.colors.primary]
background = "#1F1F28"
foreground = "#DCD7BA"

[schemes.kanagawa.colors.normal]
black = "#090618"
red = "#C34043"
green = "#76946A"
yellow = "#C0A36E"
blue = "#7E9CD8"
magenta = "#957FB8"
cyan = "#6A9589"
white = "#DCD7BA"

[schemes.kanagawa.colors.bright]
black = "#727169"
red = "#E82424"
green = "#98BB6C"
yellow = "#E6C384"
blue = "#7FB4CA"
magenta = "#938AA9"
cyan = "#7AA89F"
white = "#C8C093"

[schemes.kanagawa.colors.selection]
background = "#2D4F67"
foreground = "#C8C093"

[schemes.kanagawa.colors.cursor]
cursor = "#969384"

[schemes.lunaria_eclipse2.colors.primary]
background = "#192125"
foreground = "#C9CDD7"

[schemes.lunaria_eclipse2.colors.normal]
black = "#323F46"
red = "#83615B"
green = "#7F9781"
yellow = "#A69875"
blue = "#68668B"
magenta = "#856880"
cyan = "#7D96B2"
white = "#C9CDD7"

[schemes.lunaria_eclipse2.colors.bright]
black = "#3D4950"
red = "#BA9088"
green = "#BEDBC1"
yellow = "#F1DFB4"
blue = "#8C8ABA"
magenta = "#BE9CB8"
cyan = "#BCDBFF"
white = "#DFE2ED"

[schemes.lunaria_eclipse2.colors.selection]
background = "#7793A0"
foreground = "#DFE2ED"

[schemes.lunaria_eclipse2.colors.cursor]
cursor = "#68668B"

[schemes.lavandula2.colors.primary]
background = "#050014"
foreground = "#C6BBD5"

[schemes.lavandula2.colors.normal]
black = "#140033"
red = "#7D1625"
green = "#276458"
yellow = "#B39B68"
blue = "#746CB8"
magenta = "#5A3F7F"
cyan = "#58777F"
white = "#C6BBD5"

[schemes.lavandula2.colors.bright]
black = "#63537C"
red = "#E05167"
green = "#52E0C4"
yellow = "#E0C386"
blue = "#8E87E0"
magenta = "#A776E0"
cyan = "#9AD4E0"
white = "#D8CCE9"

[schemes.lavandula2.colors.selection]
background = "#3B2369"
foreground = "#D8CCE9"

[schemes.lavandula2.colors.cursor]
cursor = "#C6BBD5"

[schemes.neutron.colors.primary]
background = "#1C1E22"
foreground = "#E6E8EF"

[schemes.neutron.colors.normal]
black = "#23252B"
red = "#B54036"
green = "#5AB977"
yellow = "#DEB566"
blue = "#6A7C93"
magenta = "#A4799D"
cyan = "#3F94A8"
white = "#E6E8EF"

[schemes.neutron.colors.bright]
black = "#868D9F"
red = "#B54036"
green = "#5AB977"
yellow = "#DEB566"
blue = "#6A7C93"
magenta = "#A4799D"
cyan = "#3F94A8"
white = "#EBEDF2"

[schemes.neutron.colors.selection]
background = "#636973"
foreground = "#EBEDF2"

[schemes.neutron.colors.cursor]
cursor = "#E6E8EF"

[schemes.night.colors.primary]
background = "#040B14"
foreground = "#B6B3E4"

[schemes.night.colors.normal]
black = "#0A2140"
red = "#6F52C8"
green = "#187B67"
yellow = "#D199AA"
blue = "#1F66C2"
magenta = "#A4799D"
cyan = "#386BAD"
white = "#B6B3E4"

[schemes.night.colors.bright]
black = "#6282B5"
red = "#886CE5"
green = "#2FCDAD"
yellow = "#FFBACE"
blue = "#3A77D6"
magenta = "#BF8EB7"
cyan = "#4B8CDF"
white = "#D1C9FF"

[schemes.night.colors.selection]
background = "#1E58A5"
foreground = "#D1C9FF"

[schemes.night.colors.cursor]
cursor = "#674CBA"